services:
  angular_app:
    build:
      context: ../frontend
      dockerfile: Dockerfile-dev
    ports:
      - "4200:80"
    depends_on:
      spring_boot_app:
        condition: service_healthy
  spring_boot_app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      postgresql_db:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
        - "8080:8080"
    env_file:
      - ../backend/.env
  postgresql_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ../database/.env