services:
  nginx_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the config file
    depends_on:
      - public_frontend
      - private_frontend
      - spring_boot_app

  public_frontend:
    build:
      context: ../public-frontend
      dockerfile: Dockerfile-dev

  private_frontend:
    build:
      context: ../private-frontend
      dockerfile: Dockerfile-dev

  spring_boot_app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      postgresql_db:
        condition: service_started
    env_file:
      - ../backend/.env

  postgresql_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env