spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  mail:
    host: mailhog
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
info:
  application:
    name: backend
    description: Backend service
    author: Peter Červeň
    version: 1.0.0
server:
  port: 8080
frontend:
  public:
    url: ${PUBLIC_FRONTEND_URL}
  private:
    url: ${PRIVATE_FRONTEND_URL}